### ISSUE TITLE
Task Loader Mapping: Namespace Logic?

### ISSUE THREAD

**Issue by valentinaschueller** [valentinaschueller/ece-4-monitoring#15]
Tasks are related to different components of EC-Earth, e.g. computational performance, OpenIFS, Nemo. Where should this structure be visible? Idea:

```yaml
ece.mon.nemo.global_avg:
     - ...
ece.mon.oifs.global_avg:
     - ...
```
